node:
  image: triptyk/node
  ports:
    - "8000:8000"
  volumes:
    - ./server:/server
    - ./environment:/environment
    - ./logs:/root/.pm2/logs
mongo:
  image: mongo
  volumes:
    - ./dump:/dump
  ports:
    - "27017:27017"
    - "28017:28017"
